### PR TITLE
Loading

### PR DESCRIPTION
**Pull request by styled-man**
Created the loading template for when the user click find a game.

### CODE REVIEW

**Review by GabrielPedroza — COMMENTED** [review]
I pulled the PR but I'm not sure if it is on my end but the problems and playground page do not open for me. Also, how do I get to the loading page to see how the loading page looks like?

**Comment by styled-man** [comment]
> I pulled the PR but I'm not sure if it is on my end but the problems and playground page do not open for me. Also, how do I get to the loading page to see how the loading page looks like?

Since this will appear after you start looking for a game, I did not put it on any pages, I only created it. 
To view, you will have to render it on a page.

```tsx
// page.tsx
import Loading from "@/templates/Loading";

const Page = () => {
  return (
    <>
      <Loading onCancel={() => {}} />
    </>
  );
}

export default Page

**Comment by styled-man** [comment]
Ignore my previous comment, I have implemented this feature into the `/menu` route. click on one of the buttons labeled `Play `Now` and the loading screen will appear

**Comment by GabrielPedroza** [comment]
Screenshot 2022-11-09 at 9 26 01 AM

`Error: Rendered more hooks than during the previous render.`

Got this error when clicking code clash menu in the landing page

**Comment by GabrielPedroza** [comment]
YESSSSS!!! Flawless execution!

**Review by GabrielPedroza — APPROVED** [review]
God tier!

**Review by 02danieljonas — CHANGES_REQUESTED** [review]
Great job but I do have some changes. 
1. I don't think the `VS` element should be the same style as the cancel button.
2. The cancel button should have some type of on hover

And please don't Tunnel vision on tailwind, CSS is still available for when a custom style is needed.

**Review by 02danieljonas — APPROVED** [review]

**Review by 02danieljonas — APPROVED** [review]

**Pull request merged**
