### PR TITLE
added gilroy font

### PR DESCRIPTION
**Pull request by styled-man**
Downloaded the gilroy font and configured it.

### CODE REVIEW

**Comment by 02danieljonas** [comment]
LGTM!!

**Review by 02danieljonas — APPROVED** [review]
LGTM!!

**Comment by GabrielPedroza** [comment]
Why was `PORT=8000` removed from package.json? The reason why I put it there is because my machine, and I assume others, have a default port that isn't 8000 (mine is 3000) so the mock-backend script wouldn't work. Is there any issue on having it?

**Comment by 02danieljonas** [comment]
> Why was `PORT=8000` removed from package.json? The reason why I put it there is because my machine, and I assume others, have a default port that isn't 8000 (mine is 3000) so the mock-backend script wouldn't work. Is there any issue on having it?

```PORT=8000 next dev``` doesn't work for me, I found a work around ```next dev -p 8000```

**Comment by GabrielPedroza** [comment]
@02danieljonas Thanks for letting me know and just ran it locally and works for me. Merged

**Pull request merged**
